# docker-compose.yml
version: '3'
services:
  app:
    image: lostnrecover/lostnrecover:1.0
    hostname: app
    build:
    # build from Dockerfile
      context: .
      dockerfile: Dockerfile
    ports:
    - "4000:${PORT:-3000}"
    links: 
    - mongodb
    depends_on:
    - mongodb
    environment:
      APP_NAME: "Lost n Recover"
    networks:
    - internal
  mongodb:
    image: mongo:latest
    hostname: mongodb
    volumes:
    - "dbdata:/data/db"
    networks:
    - internal

volumes:
  dbdata:
networks:
  internal: 
